name: BlueZ MIDI COPR Automation

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch: # Allow manual triggering

env:
  COPR_OWNER: ${{ vars.COPR_OWNER || github.repository_owner }}

jobs:
  bluez-midi-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up COPR CLI configuration
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr << EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = ${{ vars.COPR_OWNER || github.repository_owner }}
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Run automation
        if: ${{ !inputs.fedora_version }}
        run: |
          # Mount COPR config into container and run automation
          docker build -t bluez-midi-copr .
          docker run --rm \
            -v "$PWD:/workspace" \
            -v "$HOME/.config/copr:/root/.config/copr:ro" \
            -w /workspace \
            -e COPR_OWNER="${{ env.COPR_OWNER }}" \
            bluez-midi-copr \
            ./update.sh
